### ISSUE TITLE
Freezes after copying phantom js from extracted folder

### ISSUE THREAD

**Issue by pedroaugustofr** [nosco/phantomjs-server#7]
Hello, I'm trying to install phantomjs-server but I'm always beign stucked.

When I run:

```
npm install phantomjs-server
```

npm install freezes when this line is printed:

```
Copying extracted folder /var/folders/rq/n3d887yn16gd_82s1yll0dk40000gn/T/phantomjs/phantomjs-1.9.7-macosx.zip-extract-1457104670057/phantomjs-1.9.7-macosx -> /<my_project_folder>/node_modules/phantomjs/lib/phantom
```

But if I look inside _<my_project_folder>/node_modules/phantomjs/lib/phantom_ the executable is there.

**Comment by rgembalik** [comment]
The same here

**Comment by tristobal** [comment]
I have the same error too U_U

**Comment by ehartford** [comment]
+1

    npm install phantomjs-server 

just hangs at step

    Copying extracted folder /var/folders/66/19r4n59x06nbz7m72x94g_wwrr570k/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1476999495014/phantomjs-1.9.8-macosx -> ...

**Comment by yutiansut** [comment]
+1 just hang up
